services:
  app:
    build: ./BeastTimesheet/
    image: beast-timesheet-app
    ports:
      - "127.0.0.1:5000:80"
  db:
    image: postgres
    ports:
      - "5001:5432"
    environment:
      POSTGRES_PASSWORD: db_password
